# Generated by Django 5.1.1 on 2024-11-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_autor_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
