# Generated by Django 5.1.1 on 2024-11-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_libro_descripcion_alter_libro_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion_es',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
